[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hodawang/course_3.0/blob/main/02_ML/part2/Chapter1/Data_Normalization_Example.ipynb)

In [3]:
# practice
from sklearn import preprocessing
import numpy as np

In [ ]:
from sklearn import preprocessing
import numpy as np

In [15]:
a = np.array([[10,3,4,20], 
        [-123, 3, 20, 5],
        [120,20,30,60]],
        dtype = np.float64
      )
a

array([[  10.,    3.,    4.,   20.],
       [-123.,    3.,   20.,    5.],
       [ 120.,   20.,   30.,   60.]])

In [20]:
a = np.array([[10, 2.7, 3.6, 5], [-100, 5, -2, 10], [120, 20, 40, 50]],
             dtype=np.float64)
print(a)

[[  10.     2.7    3.6    5. ]
 [-100.     5.    -2.    10. ]
 [ 120.    20.    40.    50. ]]


In [19]:
print(a)
scale_a = preprocessing.scale(a, axis=0)
print(scale_a)
scale_a = preprocessing.scale(a, axis=1)
print(scale_a)

minmax_range=(0, 1)
              
scale_a = preprocessing.minmax_scale(a, axis=1, feature_range=minmax_range)
print(scale_a)

[[  10.    3.    4.   20.]
 [-123.    3.   20.    5.]
 [ 120.   20.   30.   60.]]
[[ 0.07716644 -0.70710678 -1.30740289 -0.35897908]
 [-1.2615035  -0.70710678  0.18677184 -1.00514142]
 [ 1.18433706  1.41421356  1.12063105  1.3641205 ]]
[[ 0.11095901 -0.9246584  -0.77671306  1.59041245]
 [-1.72077668  0.46378616  0.75852876  0.49846176]
 [ 1.60375075 -0.96225045 -0.70565033  0.06415003]]
[[0.41176471 0.         0.05882353 1.        ]
 [0.         0.88111888 1.         0.8951049 ]
 [1.         0.         0.1        0.4       ]]


In [21]:
def normalize(x, axis, method, minmax_range=(0, 1)):
    if method == 'z-score':
        scale_a = preprocessing.scale(x, axis=axis)
    elif method == 'minmax':
        scale_a = preprocessing.minmax_scale(
            x, axis=axis,
            feature_range=minmax_range)  # default feature range 0~1
    return scale_a

# Z-Score

In [23]:
# 改變axis，看看結果如何變化
axis = 1
scale_a = normalize(a, axis, method='z-score')
print(scale_a)

[[ 1.65733517 -0.93058927 -0.61153009 -0.11521581]
 [-1.72439359  0.58948918  0.43523033  0.69967408]
 [ 1.65930828 -0.99558497 -0.46460632 -0.19911699]]


In [ ]:
print(scale_a.std(axis=axis))
print(scale_a.mean(axis=axis))

# Maxmin Scale

In [29]:
# 改變axis，看看結果如何變化
axis = 0
# 改變minmax_range看看結果如何變化
scale_a = normalize(a, axis, method='minmax', minmax_range=(0, 1))
print(scale_a)

[[0.5        0.         0.13333333 0.        ]
 [0.         0.13294798 0.         0.11111111]
 [1.         1.         1.         1.        ]]


In [30]:
print(scale_a.max(axis=axis))
print(scale_a.min(axis=axis))

[1. 1. 1. 1.]
[0. 0. 0. 0.]
