[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hodawang/course_3.0/blob/main/02_ML/part2/Chapter1/Training_and_Testing_Data_Split_Example.ipynb)

# Import Library

In [ ]:
from sklearn.model_selection import train_test_split
import numpy as np

In [8]:
from sklearn.model_selection import train_test_split
import numpy as np
X, y = np.arange(50).reshape(10, 5), np.arange(10)
print('X:',X)
print('y:',y)

X: [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
y: [0 1 2 3 4 5 6 7 8 9]


# Create dataset

In [22]:
X, y = np.arange(50).reshape(10, 5), np.arange(10)  #第一個維度必需一樣，否則無法分割

In [ ]:
print('X: shape' + str(X.shape))
print(X)
print('y: shape' + str(y.shape))
print(y)

# Training & Testing Data Split

In [ ]:
# trying to tune shuffle and random_state
X_train, X_test, y_train, y_test = train_test_split(X,
      y,
      test_size=0.33,
      random_state=42,
      shuffle=False)

In [ ]:
X_train

In [ ]:
y_train

In [23]:
x_train, x_test, y_train, y_test = train_test_split(
      X, y,
      test_size=0.2111,
      random_state = 10,
      shuffle=True)
print('----- Org ------')
print(X, y)
print('----- x ------')
print(x_train.shape)
print(x_train)
print(x_test)
print('------ y ------')
print(y_train.shape)
print(y_train)
print(y_test)

----- Org ------
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]] [0 1 2 3 4 5 6 7 8 9]
----- x ------
(7, 5)
[[30 31 32 33 34]
 [15 16 17 18 19]
 [ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [35 36 37 38 39]
 [20 21 22 23 24]
 [45 46 47 48 49]]
[[40 41 42 43 44]
 [10 11 12 13 14]
 [25 26 27 28 29]]
------ y ------
(7,)
[6 3 1 0 7 4 9]
[8 2 5]
